Use copyright in errors and view template
NorthPage/calamum pull request #1
Opened 2020-05-19 19:56 UTC by jeremyweber-np

Use copyright in errors and view template

2020-05-19 20:39 UTC, cgatesman requested changes

2020-05-19 20:39 UTC, cgatesman commented on CHANGELOG.md
> +1.2.3(19/05/2021)
2021?

2020-05-19 20:39 UTC, cgatesman commented on CHANGELOG.md
>  1.2.2(27/11/2014)
What's up with the European dates?

2020-05-20 14:24 UTC, jeremyweber-np commented on CHANGELOG.md
>  1.2.2(27/11/2014)
This a fork of another project...

2020-05-22 19:25 UTC, cgatesman approved these changes

2020-05-28 19:02 UTC, merged